 CREATE TABLE AUTHOR (id SERIAL PRIMARY KEY, FIRST_NAME VARCHAR, LAST_NAME VARCHAR);
 CREATE TABLE GENRE (id SERIAL PRIMARY KEY, NAME CHAR(50));
 CREATE TABLE SOURCE (id SERIAL PRIMARY KEY, NAME CHAR(50));
 CREATE TABLE LABEL (id SERIAL PRIMARY KEY, TITLE CHAR(50), COLOR CHAR(20));

CREATE TABLE ITEM (ID SERIAL PRIMARY KEY, AUTHOR VARCHAR, SOURCE VARCHAR, LABEL CHAR(50), PUBLISHED_DATE DATE, FOREIGN KEY (id) REFERENCES Author(id),
FOREIGN KEY (id) REFERENCES GENRE(id) FOREIGN KEY (id) REFERENCES SOURCE(id),FOREIGN KEY (id) REFERENCES LABEL(id), ARCHIVED BOOLEAN);

 CREATE TABLE MOVIE (ID SERIAL PRIMARY KEY, AUTHOR VARCHAR, SOURCE VARCHAR, LABEL CHAR(50), PUBLISHED_DATE DATE, ARCHIVED BOOLEAN, SILET BOOLEAN);
 CREATE TABLE BOOK (ID SERIAL PRIMARY KEY, AUTHOR VARCHAR, SOURCE VARCHAR, LABEL CHAR(50), PUBLISHED_DATE DATE, ARCHIVED BOOLEAN, PUBLISHER VARCHAR, COVER_STATE CHAR(10));
 CREATE TABLE GAME (ID SERIAL PRIMARY KEY, AUTHOR VARCHAR, SOURCE VARCHAR, LABEL CHAR(50), PUBLISHED_DATE DATE, ARCHIVED BOOLEAN, MULTI_PLAYER BOOLEAN, LAST_PLAYED_AT DATE);
 CREATE TABLE MusicAlbum (ID SERIAL PRIMARY KEY, AUTHOR VARCHAR, SOURCE VARCHAR, LABEL CHAR(50), PUBLISHED_DATE DATE, ARCHIVED BOOLEAN, ON_SPOTIFY BOOLEAN);
